language: minimal
services:
- docker
before_install:
- bash scripts/build.sh
deploy:
  provider: script
  script: bash scripts/deploy.sh
  on:
    branch: master
env:
  global:
  - secure: dDu6SxmMr7euTwVAQj9r6XqkoLBFw6Znk2IV4Rg6H504nMutRRJ4M7MLiU2VQNXOQkfX4gL3U0HxbxxbHoUHrCRp9dQv/HYx4glJHWAMVMDC8gZ62QQTnWrm89a6UY57b+u+xuCpNSodadcdSMGjcHW5py9DqMuht5vztTPdwdS2izX6ihkX3tsglddc5Vo7sCwuxLxFAJfmnNhOV0pKpKx8XiXZG2fc/2ro6QKj6wgFHTMyarV7urlKoz6YBz0aEkZRtTIyARBDJ/fbjkBKSWW7sVqFTLbJ6OxVk93rwDpNSyvyvhg53US6ix4x3vGUD/035Sl924GNdlj2umcl/oplHOzHhcuJrHgmt03JJCI3ysNfOi34IMIjLe5oHWPlu/jaDf21SBmJVqXQQO9cmWPFN5EXLJ1S/33lI8H9GGFCrKC8Op17b7jUeebaFQ9tH40MnC1+5QzClr4vnoWhEa2PA5itzP8gnXJ1eBLFr/mQj1fqQpvm3Q+daKCbTfZ3Qy/5kFCcYXfu/xxeUnVPTz9s5Nuf+87KckJ6V1mDVPAO+XWduJEl+1adQOO2TEWPRPUOAA7LMQ6VCqaoD7wszKUvMWgm4vSar8hRybLwJXnbyxylIQZgQOBm+Oauq0FGpw4DvKKgTTLBOnLO21/Rb9kCGqnY6JzD70qtF7obT1M=
  - secure: oFFi9va06+qkR5s21h2fwQVKoD8sN3atA7kpvtwCqBXTjxBoEASCrG3DQ5MTUlqTIUN5EpGryuQfm50FNVPKxkWtDGapbxuNPeqz1OnlmiQg5tFL+q53NplKlp9tqdSaTc3g377N+/9oCikRx3GA4fiP5NYaGnq/Tda+89qCxsWOHf5qulkOkEZJx+HyPhRp2LWHYT2yeTDtsGnAjUTIS4gznQ0faXbhExjTsxPfTbS5Y+6L84tXH1txxe9PbZWpL5XQZ1LI8aVBIoKGFFb8r1SI2m4KSnqTE49HTdSVk+w89zeYyyE4L5mszSf2pFx6IM7qcn0Bc2zVDkEoz3c1lU+c6G5YPnJSEgTVMzfwbKbyV5rh5MGgViaMKoIKXqPpBndlk45RQXRe76naLxRg4D0mbOgyswBbmzQc595VByv9mQ1jEQARRA+y6Yp/imAKjihz3dF3r68KbFJhfMVG28F5zEhugGv6eHrT7YddXsUSJ7gOYh3uhEtEB2WhrSYQcFnUICBH6nRhauiGQ14+jZa1X19FgUEW8vI3QGDaqcYfm+kRlv5qeqB8PQlZqpus6FtwiapXQVDJQ+5rVojCaeS2JITaD+aHJpJYbARmVEWdmFalxoiLwHN3NSYjIsIF2cR5OdrLffvkvwMJGDsybZpz/MS7XuXU6SBHap/3zsw=
